export const ALL_MATCHS_REQUEST = "ALL_MATCHS_REQUEST";
export const ALL_MATCHS_SUCCESS = "ALL_MATCHS_SUCCESS";
export const ALL_MATCHS_FAIL = "ALL_MATCHS_FAIL";

export const MATCH_DETAILS_REQUEST = "MATCH_DETAILS_REQUEST";
export const MATCH_DETAILS_SUCCESS = "MATCH_DETAILS_SUCCESS";
export const MATCH_DETAILS_FAIL = "MATCH_DETAILS_FAIL";
// auth actions-types :
// LOGIN
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
// REGISTER :
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
// LOAD :
export const LOAD_REQUEST = "LOAD_REQUEST";
export const LOAD_SUCCESS = "LOAD_SUCCESS";
export const LOAD_FAIL = "LOAD_FAIL";
// LOGOUT :
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
// admin actions-types :
export const ADMIN_MATCHS_REQUEST = "ADMIN_MATCHS_REQUEST";
export const ADMIN_MATCHS_SUCCESS = "ADMIN_MATCHS_SUCCESS";
export const ADMIN_MATCHS_FAIL = "ADMIN_MATCHS_FAIL";
// admin delete matchs
export const DELETE_MATCH_REQUEST = "DELETE_MATCH_REQUEST";
export const DELETE_MATCH_SUCCESS = "DELETE_MATCH_SUCCESS";
export const DELETE_MATCH_RESET = "DELETE_MATCH_RESET";
export const DELETE_MATCH_FAIL = "DELETE_MATCH_FAIL";
export const UPDATE_MATCH_REQUEST = "UPDATE_MATCH_REQUEST ";
export const UPDATE_MATCH_SUCCESS = " UPDATE_MATCH_SUCCESS";

export const UPDATE_MATCH_RESET = "UPDATE_MATCH_RESET";
export const UPDATE_MATCH_FAIL = "UPDATE_MATCH_FAIL";
export const NEW_MATCH_REQUEST = "NEW_MATCH_REQUEST";
export const NEW_MATCH_SUCCESS = "NEW_MATCH_SUCCESS";
export const NEW_MATCH_RESET = "NEW_MATCH_RESET";
export const NEW_MATCH_FAIL = "NEW_MATCH_FAIL";
// user actions :
export const ALL_USERS_REQUEST = "ALL_USERS_REQUEST";
export const ALL_USERS_SUCCESS = "ALL_USERS_SUCCESS";
export const ALL_USERS_FAIL = "ALL_USERS_FAIL";
// update profile :
export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET";
